### ISSUE TITLE
Deployment support scenario

### ISSUE THREAD

**Issue by grandrew** [criticalhop/kalc#96]
Execution scenario:

1. [x] `has_deployment_creates_daemonset__pods_evicted_pods_pending` Customer has a deployment, creates daemonset (with high priority), some (at least one) deployment pods get evicted => we detect an issue in cluster (severity depends on amount of pods not able to schedule)
2. [x] `creates_deployment_but_insufficient_resource__pods_pending` Customer creates a new Deployment, not all pods of deployment were able to run (severity as in 1)
3. [x] `creates_service_and_deployment_insufficient_resource__service_outage` Customer creates a Service and a Deployment, no pods were able to run for Service, we detect Service outage event (severity 1.0)
4. [x] `has_deployment_creates_deployment__pods_evicted_pods_pending` Customer has a Deployment, creates a new Deployment with higher priority, original deployments' pods get evicted and not being able to run (at least one pod) => We detect an issue, severity depends on amount of pods we were not able to schedule
    1. [ ] calculate severity (at least add mechanism to allow severity calculation) - need to see what deployment was interrupted (or that THE deployment was interrupted) 
5. [x] `has_daemonset_creates_deployment__pods_pending_high_severity` Customer has a DaemonSet, creates a Deployment with higher priority, one of the pods for DaemonSet gets evicted => we detect a high-severity issue (because DaemonSet only has 1 pod per node working)
    1. [ ] calculate severity (at least add mechanism to allow severity calculation) - need to see what daemonset was interrupted (or that THE daemonset was interrupted) 
6. [ ] `exclude_has_daemonset_creates_deployment__hybrid_issue_service_pods` Customer has a DaemonSet, creates a Deployment with higher priority, ALSO  Customer creates a Service and a Deployment, no pods were able to run for Service, we detect Service outage event. Customer is able to detect both of these scenarios by "excluding" any of the first that was found
7. [ ] `exclude_till_cluster_clean` test must still pass
8, [ ] Customer creates a Service and a Deployment, SOME pods were able to run for Service, we detect `PodsInPendingStateIssue`

How customer is using the program:

1. `kubectl-val -d cluster_dump/ -f daemonset_create.yaml`
2. `kubectl-val -d cluster_dump/ -f deployment_create.yaml`
3. `kubectl-val -d cluster_dump/ -f deployment_service_create.yaml`
4. `kubectl-val -d cluster_dump/ -f deployment_create.yaml` -> `... ... PodsInPendingStateIssue`
5. `kubectl-val -d cluster_dump/ -f deployment_create.yaml`
6. Multiple steps: `kubectl-val -d cluster_dump/ -f deployment_create.yaml`, then `kubectl-val -d cluster_dump/ -f deployment_create.yaml -e "Deployment:redis-master"` - do "exclude" to find all scenarios

YAML report that Customer will get for `PodsInPendingStateIssue` issue ends with the following:

(it starts with any steps found by the planner but in every check that detects `PodsInPendingStateIssue` ends with YAML part as shown below:

```yaml
# Loading cluster definitions from tests/daemonset_eviction/cluster_dump/ ...
# Creating resource from tests/daemonset_eviction/daemonset_create.yaml ...
# Building abstract state ...
# Solving ...
# Scenario found.
probability: 1.0
severity: 0.67
steps:
# ... (skipped many steps) ...
- affected:
  - kind: Deployment
    metadata:
      name: redis-master
  description: Pods left in "Pending" state
  name: PodsInPendingStateIssue
  parameters:
    service:
      kind: Deployment
      metadata:
        name: redis-master
    deployment.amountOfActivePods: 2
    deployment.replicas: 3
  probability: 1.0
  severity: 0.67
  subsystem: AnyServiceInterrupted
```

Reasoning: we need to be able to programmatically exclude the found scenario, therefore we need to have the last step in scenario that will indicate what to "exclude"

- [ ] Export "scenario summary" that will tell exactly what to exclude to find next scenario
